Repository qiniu/android-sdk, pull requests merged in 2020-11, with the labels that each got.

#434 change configuration annotation
  library/library.iml
  library/src/main/java/com/qiniu/android/storage/Configuration.java
  library/src/main/java/com/qiniu/android/storage/GlobalConfiguration.java
Labels: size/S

#435 Develop to master
  .gitignore
  CHANGELOG.md
  README.md
  library/build.gradle
  library/library.iml
  library/src/androidTest/java/com/qiniu/android/ConcurrentResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/FastDatePrinterTest.java
  library/src/androidTest/java/com/qiniu/android/ResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/TestConfig.java
  library/src/main/java/com/qiniu/android/common/Constants.java
  library/src/main/java/com/qiniu/android/http/ResponseInfo.java
  library/src/main/java/com/qiniu/android/http/dns/DnsCacheInfo.java
  library/src/main/java/com/qiniu/android/http/dns/DnsPrefetcher.java
  library/src/main/java/com/qiniu/android/http/request/HttpRegionRequest.java
  library/src/main/java/com/qiniu/android/http/request/IUploadRegion.java
  library/src/main/java/com/qiniu/android/http/request/Request.java
  library/src/main/java/com/qiniu/android/http/request/httpclient/SystemHttpClient.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadDomainRegion.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadServerFreezeManager.java
  library/src/main/java/com/qiniu/android/storage/Configuration.java
  library/src/main/java/com/qiniu/android/storage/GlobalConfiguration.java
  library/src/main/java/com/qiniu/android/storage/PartsUpload.java
  library/src/main/java/com/qiniu/android/utils/Utils.java
Labels: size/L

#436 check network permission
  library/library.iml
  library/src/main/java/com/qiniu/android/utils/AndroidNetwork.java
Labels: size/S

#441 optimize some code
  .idea/misc.xml
  .idea/modules.xml
  CHANGELOG.md
  README.md
  library/build.gradle
  library/library.iml
  library/src/androidTest/java/com/qiniu/android/ConcurrentResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/ResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/RetryTest.java
  library/src/androidTest/java/com/qiniu/android/TokenTest.java
  library/src/androidTest/java/com/qiniu/android/UploadDomainRegionTest.java
  library/src/androidTest/java/com/qiniu/android/UploadServerFreezeManagerTest.java
  library/src/main/java/com/qiniu/android/common/Constants.java
  library/src/main/java/com/qiniu/android/http/ResponseInfo.java
  library/src/main/java/com/qiniu/android/http/metrics/UploadRegionRequestMetrics.java
  library/src/main/java/com/qiniu/android/http/request/HttpRegionRequest.java
  library/src/main/java/com/qiniu/android/http/request/HttpSingleRequest.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadDomainRegion.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadServerFreezeManager.java
  library/src/main/java/com/qiniu/android/storage/ConcurrentResumeUpload.java
  library/src/main/java/com/qiniu/android/storage/GlobalConfiguration.java
  library/src/main/java/com/qiniu/android/storage/PartsUpload.java
  library/src/main/java/com/qiniu/android/storage/ResumeUpload.java
  library/src/main/java/com/qiniu/android/utils/AndroidNetwork.java
  library/src/main/java/com/qiniu/android/utils/Utils.java
Labels: size/XL

#442 发布v8.0.5
  .idea/misc.xml
  .idea/modules.xml
  CHANGELOG.md
  README.md
  library/build.gradle
  library/library.iml
  library/src/androidTest/java/com/qiniu/android/ConcurrentResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/ResumeUploadTest.java
  library/src/androidTest/java/com/qiniu/android/RetryTest.java
  library/src/androidTest/java/com/qiniu/android/TokenTest.java
  library/src/androidTest/java/com/qiniu/android/UploadDomainRegionTest.java
  library/src/androidTest/java/com/qiniu/android/UploadServerFreezeManagerTest.java
  library/src/main/java/com/qiniu/android/common/Constants.java
  library/src/main/java/com/qiniu/android/http/ResponseInfo.java
  library/src/main/java/com/qiniu/android/http/metrics/UploadRegionRequestMetrics.java
  library/src/main/java/com/qiniu/android/http/request/HttpRegionRequest.java
  library/src/main/java/com/qiniu/android/http/request/HttpSingleRequest.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadDomainRegion.java
  library/src/main/java/com/qiniu/android/http/serverRegion/UploadServerFreezeManager.java
  library/src/main/java/com/qiniu/android/storage/ConcurrentResumeUpload.java
  library/src/main/java/com/qiniu/android/storage/GlobalConfiguration.java
  library/src/main/java/com/qiniu/android/storage/PartsUpload.java
  library/src/main/java/com/qiniu/android/storage/ResumeUpload.java
  library/src/main/java/com/qiniu/android/utils/AndroidNetwork.java
  library/src/main/java/com/qiniu/android/utils/Utils.java
Labels: size/XL
